### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by suryaelidanto** [fathonix/ChatGPT-WhatsApp#2]
i've been scan it, and it says connected like this image :
![image](https://user-images.githubusercontent.com/50188897/220144976-fe0b547c-c2c3-4391-806d-27451c9414f9.png)

so i want to try the command, where do i do it?

thanks!

**Comment by suryaelidanto** [comment]
Btw, i can't use the command inside the cmd or terminal, i don't know how to use it

**Comment by fathonix** [comment]
Sekarang wa agan yang disambungin jadi bot, jadi coba kirim pake wa lain ke wa yang udah disambungin gan. Kalo di .env udah diset `PREFIX_ENABLED` jadi `true` ntar ngirim ke botnya pake prefix default atau yang udah diatur di `PREFIX_KEY`.

Your WhatsApp account now acts as the bot, so you can text the command to the bot account with other accounts. If you set `PREFIX_ENABLED` to `true` in the .env, you should be able to send with the default prefix or the custom one set in `PREFIX_KEY`.

**Comment by suryaelidanto** [comment]
> Sekarang wa agan yang disambungin jadi bot, jadi coba kirim pake wa lain ke wa yang udah disambungin gan. Kalo di .env udah diset `PREFIX_ENABLED` jadi `true` ntar ngirim ke botnya pake prefix default atau yang udah diatur di `PREFIX_KEY`.
> 
> Your WhatsApp account now acts as the bot, so you can text the command to the bot account with other accounts. If you set `PREFIX_ENABLED` to `true` in the .env, you should be able to send with the default prefix or the custom one set in `PREFIX_KEY`.

ah i see, oke thanks gan
